language: python
# branches:
#  only:
#    - master
os:
  - linux
python:
  - "2.7"
sudo: false
install:
  - make install
  #- make start
#before_script:
#  - sleep 5
script:
  - make test
  - make pep8
