name: twitcher
channels:
- birdhouse
- defaults
- conda-forge
dependencies:
- python=2.7
- six
- curl
- pyopenssl
- cryptography
- mako
- pyyaml
- icu=56
# tests
- pytest
- flake8
- mock
- pbr
- webtest
# sphinx
- sphinx
# twitcher
- argcomplete
- lxml=3.7
- libxslt=1.1.29
- paste
- pastedeploy
- requests
- requests-oauthlib
- webob
# pywps
- pywps=4.0.0
# nginx, supervisor
- nginx=1.10
- supervisor=3
- gunicorn=19
- gevent=1.2
# mongodb
- pymongo=3
- mongodb=3.4
- pip:
  - genshi==0.7
  - pyramid-rpc
  - sphinx-autoapi
  - -e git+https://github.com/huard/sphinx-autodoc-pywps.git#egg=sphinx_autodoc_pywps
